package study.spring_boot_c.domain.product.domain.enums;

public enum Category {
    DIGITAL_MACHINE,HOME_APPLIANCES,INTERIOR,BABY, PROCESSED_FOOD, BABY_BOOKS, SPORTS, WOMEN_ACCESSORIES, WOMEN_CLOTHING, MEN_ACCESSORIES, MEN_CLOTHING, GAME, BEAUTY, PET, BOOKS, TICKETS, MUSIC, PLANTS, ETC
}
